/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: ["./index.html","./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      fontFamily: {
        sans: ["Inter","system-ui","-apple-system","sans-serif"],
        mono: ["JetBrains Mono","Fira Code","monospace"],
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        xl:  "1rem",
        "2xl": "1.25rem",
        "3xl": "1.5rem",
      },
      colors: {
        background:  "hsl(var(--background))",
        foreground:  "hsl(var(--foreground))",
        card:        { DEFAULT: "hsl(var(--card))",        foreground: "hsl(var(--card-foreground))"        },
        popover:     { DEFAULT: "hsl(var(--popover))",     foreground: "hsl(var(--popover-foreground))"     },
        primary:     { DEFAULT: "hsl(var(--primary))",     foreground: "hsl(var(--primary-foreground))"     },
        secondary:   { DEFAULT: "hsl(var(--secondary))",   foreground: "hsl(var(--secondary-foreground))"   },
        muted:       { DEFAULT: "hsl(var(--muted))",       foreground: "hsl(var(--muted-foreground))"       },
        accent:      { DEFAULT: "hsl(var(--accent))",      foreground: "hsl(var(--accent-foreground))"      },
        destructive: { DEFAULT: "hsl(var(--destructive))", foreground: "hsl(var(--destructive-foreground))" },
        border:   "hsl(var(--border))",
        input:    "hsl(var(--input))",
        ring:     "hsl(var(--ring))",
        success:  "hsl(var(--success))",
        warning:  "hsl(var(--warning))",
      },
      keyframes: {
        "accordion-down": { from:{height:"0"},  to:{height:"var(--radix-accordion-content-height)"} },
        "accordion-up":   { from:{height:"var(--radix-accordion-content-height)"}, to:{height:"0"} },
        shimmer:          { "0%":{backgroundPosition:"-200% 0"}, "100%":{backgroundPosition:"200% 0"} },
        "fade-in":        { from:{opacity:0}, to:{opacity:1} },
        "slide-up":       { from:{opacity:0,transform:"translateY(16px)"}, to:{opacity:1,transform:"translateY(0)"} },
        float:            { "0%,100%":{transform:"translateY(0)"}, "50%":{transform:"translateY(-8px)"} },
      },
      animation: {
        "accordion-down": "accordion-down 0.22s ease-out",
        "accordion-up":   "accordion-up 0.22s ease-out",
        shimmer:          "shimmer 1.6s infinite",
        "fade-in":        "fade-in 0.3s ease both",
        "slide-up":       "slide-up 0.4s ease both",
        float:            "float 3s ease-in-out infinite",
      },
      boxShadow: {
        xs:       "0 1px 2px rgba(0,0,0,0.05)",
        card:     "0 1px 3px rgba(0,0,0,0.06), 0 1px 2px rgba(0,0,0,0.04)",
        elevated: "0 8px 30px rgba(99,102,241,0.15), 0 2px 8px rgba(0,0,0,0.06)",
        glow:     "0 0 20px rgba(99,102,241,0.25)",
      },
      spacing: { "18": "4.5rem" },
      screens: { xs: "375px" },
    },
  },
  plugins: [],
};
